info:
  description: Spring OAuth2 and Spring Cloud demo
  url: https://github.com/sfogo/spring-demoa2-cloud

management:
  context-path: /actuate

endpoints:
  cors:
    allowedOrigins: '*'
    allowedMethods: POST, GET, OPTIONS, DELETE
    maxAge: 3600
    allowedHeaders: x-requested-with, authorization
