logging:
  level:
    org:
      springframework:
        web: DEBUG
        security: DEBUG

server:
  port: 8091
  error:
    whitelabel:
      enabled: false

  use-forward-headers: true
  tomcat:
    port-header: x-forwarded-port
    remote_ip_header: x-forwarded-for
    protocol_header: x-forwarded-proto

---
spring:
  profiles: r1
  oauth2.resource.id: r1
---
spring:
  profiles: r2
  oauth2.resource.id: r2
---
spring:
  profiles: r3
  oauth2.resource.id: r3
---
spring:
  profiles: dev
  oauth2:
    resource:
      userInfoUri: http://localhost:8090/user
      tokenInfoUri: http://localhost:8090/oauth/check_token
      preferTokenInfo: false
---
spring:
  profiles: docker
  oauth2:
    resource:
      userInfoUri: http://authorization-server:8090/user
      tokenInfoUri: http://authorization-server:8090/oauth/check_token
      preferTokenInfo: false
